name: 06-context
on: 
 push:
 workflow_dispatch:
jobs:
   echo-data:
    runs-on: ubuntu-latest
    steps:
     - name: Display
       run: |
        echo "Event ${{github.event_name}}"
        echo "ref ${{github.ref}}"
        echo "sha ${{github.sha}}"
        echo "actor ${{github.actor}}"
        echo "run id ${{github.run_number}}"
     - name: reterive vairable
       run: |
         echo "vairable: ${{vars.MY_VAR}}"

